apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
  - ReadWriteOnce # Possible Options: ReadOnlyMany, ReadWriteOnce, ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
# Optionally you can replace "hostPath:" with another storage solution
# awsElasticBlockStore:
#   volumeID: {volume-id}
#   fsType: ext4
  