apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd-web
  name: httpd-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd-web
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-web
    spec:
      containers:
      - image: httpd
        name: httpd
        resources: {}
status: {}
